services:
  vector-aggregator:
    image: timberio/vector:latest-alpine
    container_name: vector-aggregator
    user: root
    ports:
      - "6000:6000"
    environment:
      - DEBUG_HUB=add_hub_timestamp
    volumes:
      - ./deploy/vector/vector-aggregator-hub.yaml:/etc/vector/vector.yaml:ro
      - ./services/log_parser/data:/app/data
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: grafana_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: glue-dispenser-db
    volumes:
      - /home/tarunk/OneDrive/ASM/asm-predictive-maintenance/data/glue-dispenser-db.sql:/docker-entrypoint-initdb.d/glue-dispenser-db.sql
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:12.3.2
    container_name: grafana
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./services/grafana/provisioning:/etc/grafana/provisioning
      - ./services/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
