services:
  vector-aggregator:
    image: timberio/vector:latest-alpine
    container_name: vector-aggregator
    user: root
    ports:
      - "6000:6000"
    environment:
      - DEBUG_HUB=add_hub_timestamp
    volumes:
      - ./deploy/vector/vector-aggregator-hub.yaml:/etc/vector/vector.yaml:ro
      - ./services/log_parser/data:/app/data
    restart: unless-stopped
