{
 "title": "System — Global",
 "time": { "from": "2026-02-01T18:30:00.000Z", "to": "2026-02-02T18:29:59.000Z" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "postgres" },
   {
    "name": "rolling_window",
    "query": "1 minute,5 minutes,10 minutes,15 minutes,30 minutes,1 hour"
   }
  ]
 },
 "panels": [
  {
   "title": "Cycle Time Value",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n  SELECT timestamp, value\n  FROM process_metrics\n  WHERE $__timeFilter(timestamp)\n    AND station_name = 'system'\n    AND metric_name = 'cycle_time_value'\n),\n \nbaseline AS (\n  SELECT mean, std_dev\n  FROM baseline_metrics\n  WHERE station_name = 'system'\n    AND metric_name = 'cycle_time_value'\n  LIMIT 1\n)\n \nSELECT\n  f.timestamp AS time,\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n  b.mean AS \"Mean\",\n \n  CASE\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n      OR f.value < (b.mean - 3 * b.std_dev)\n    THEN f.value\n    ELSE NULL\n  END AS anomaly_time\n \nFROM filtered f\nCROSS JOIN baseline b\nORDER BY f.timestamp;"
    },
    {
     "rawSql": "WITH base AS (\n  SELECT\n    timestamp AS time,\n    value\n  FROM process_metrics\n  WHERE $__timeFilter(timestamp)\n    AND station_name = 'system'\n    AND metric_name = 'cycle_time_value'\n),\nrolling AS (\n  SELECT\n    time,\n    AVG(value)         OVER w AS rolling_mean,\n    STDDEV_SAMP(value) OVER w AS rolling_std\n  FROM base\n  WINDOW w AS (\n    ORDER BY time\n    RANGE BETWEEN ${rolling_window:sqlstring}::interval PRECEDING\n    AND CURRENT ROW\n  )\n)\nSELECT\n  time,\n  rolling_mean,\n  rolling_mean + 3 * rolling_std AS bb_upper,\n  rolling_mean - 3 * rolling_std AS bb_lower\nFROM rolling\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Pressure Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n  SELECT timestamp, value\n  FROM process_metrics\n  WHERE $__timeFilter(timestamp)\n    AND station_name = 'system'\n    AND metric_name = 'pressure_value'\n),\n \nbaseline AS (\n  SELECT mean, std_dev\n  FROM baseline_metrics\n  WHERE station_name = 'system'\n    AND metric_name = 'pressure_value'\n  LIMIT 1\n)\n \nSELECT\n  f.timestamp AS time,\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n  b.mean AS \"Mean\",\n \n  CASE\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n      OR f.value < (b.mean - 3 * b.std_dev)\n    THEN f.value\n    ELSE NULL\n  END AS \"Anomaly\"\n \nFROM filtered f\nCROSS JOIN baseline b\nORDER BY f.timestamp;"
    }
   ]
  },
  {
   "title": "Gantry Cpk Y Upper",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n  SELECT timestamp, value\n  FROM process_metrics\n  WHERE $__timeFilter(timestamp)\n    AND station_name = 'system'\n    AND metric_name = 'gantry_cpk_y_upper'\n),\n \nbaseline AS (\n  SELECT mean, std_dev\n  FROM baseline_metrics\n  WHERE station_name = 'system'\n    AND metric_name = 'gantry_cpk_y_upper'\n  LIMIT 1\n)\n \nSELECT\n  f.timestamp AS time,\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n  b.mean AS \"Mean\",\n \n  CASE\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n      OR f.value < (b.mean - 3 * b.std_dev)\n    THEN f.value\n    ELSE NULL\n  END AS \"Anomaly\"\n \nFROM filtered f\nCROSS JOIN baseline b\nORDER BY f.timestamp;"
    }
   ]
  },
  {
   "title": "Online Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'Online_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'Online_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Dispense Speed Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mm/s" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'dispense_speed_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'dispense_speed_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Glue Weight Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'glue_weight_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'glue_weight_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Striking Time Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'striking_time_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'striking_time_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Nozzle Temp Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'nozzle_temp_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'nozzle_temp_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Single Dot Valve2 Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'single_dot_valve2_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'single_dot_valve2_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cam Uv Glue Sn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "unit" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cam_uv_glue_sn'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cam_uv_glue_sn'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Priority Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'Priority_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'Priority_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Dispense Voltage Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'dispense_voltage_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'dispense_voltage_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Tossing Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "unit" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'tossing_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'tossing_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Pulse Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'pulse_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'pulse_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Operator Id Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "unit" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'operator_id_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'operator_id_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Gantry Cpk X Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'gantry_cpk_x_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'gantry_cpk_x_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Single Dot Valve1 Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'single_dot_valve1_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'single_dot_valve1_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Raising Time Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'raising_time_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'raising_time_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Dispense Height Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'dispense_height_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'dispense_height_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Gantry Cpk Y Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'gantry_cpk_y_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'gantry_cpk_y_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 1 dispenser start point a value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_1_dispenser_start_point_a_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_1_dispenser_start_point_a_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 1 dispenser start point x value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_1_dispenser_start_point_x_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_1_dispenser_start_point_x_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 1 dispenser start point y value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_1_dispenser_start_point_y_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_1_dispenser_start_point_y_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 2 dispenser start point a value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_2_dispenser_start_point_a_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_2_dispenser_start_point_a_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 2 dispenser start point x value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_2_dispenser_start_point_x_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_2_dispenser_start_point_x_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 2 dispenser start point y value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_2_dispenser_start_point_y_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_2_dispenser_start_point_y_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 3 dispenser start point a value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_3_dispenser_start_point_a_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_3_dispenser_start_point_a_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 3 dispenser start point x value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_3_dispenser_start_point_x_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_3_dispenser_start_point_x_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 3 dispenser start point y value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_3_dispenser_start_point_y_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_3_dispenser_start_point_y_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 4 dispenser start point a value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_4_dispenser_start_point_a_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_4_dispenser_start_point_a_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 4 dispenser start point x value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_4_dispenser_start_point_x_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_4_dispenser_start_point_x_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 4 dispenser start point y value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_4_dispenser_start_point_y_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_4_dispenser_start_point_y_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 5 dispenser start point a value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_5_dispenser_start_point_a_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_5_dispenser_start_point_a_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 5 dispenser start point x value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_5_dispenser_start_point_x_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_5_dispenser_start_point_x_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 5 dispenser start point y value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_5_dispenser_start_point_y_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_5_dispenser_start_point_y_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 6 dispenser start point a value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_6_dispenser_start_point_a_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_6_dispenser_start_point_a_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 6 dispenser start point x value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_6_dispenser_start_point_x_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_6_dispenser_start_point_x_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "Cavity 6 dispenser start point y value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'cavity_6_dispenser_start_point_y_value'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'cavity_6_dispenser_start_point_y_value'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "main_valve_temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'main_valve_temp'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'main_valve_temp'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "sub_valve_temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'sub_valve_temp'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'sub_valve_temp'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  },
  {
   "title": "unique_pallet_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n\n  SELECT timestamp, value\n\n  FROM process_metrics\n\n  WHERE $__timeFilter(timestamp)\n\n    AND station_name = 'system'\n\n    AND metric_name = 'unique_pallet_count'\n\n),\n \nbaseline AS (\n\n  SELECT mean, std_dev\n\n  FROM baseline_metrics\n\n  WHERE station_name = 'system'\n\n    AND metric_name = 'unique_pallet_count'\n\n  LIMIT 1\n\n)\n \nSELECT\n\n  f.timestamp AS time,\n\n  f.value AS \"value\",\n \n  (b.mean + 3 * b.std_dev) AS \"UCL (+3σ)\",\n\n  (b.mean - 3 * b.std_dev) AS \"LCL (-3σ)\",\n\n  b.mean AS \"Mean\",\n \n  CASE\n\n    WHEN f.value > (b.mean + 3 * b.std_dev)\n\n      OR f.value < (b.mean - 3 * b.std_dev)\n\n    THEN f.value\n\n    ELSE NULL\n\n  END AS \"Anomaly\"\n \nFROM filtered f\n\nCROSS JOIN baseline b\n\nORDER BY f.timestamp;\n "
    }
   ]
  }
 ]
}