{
 "title": "STATION HEALTH SCORES",
 "tags": [
  "health",
  "stations",
  "zscore"
 ],
 "time": { "from": "2026-02-03T18:43:47.026Z", "to": "2026-02-03T19:27:42.656Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "sma_window",
    "label": "SMA Window",
    "query": "1 minute,5 minutes,10 minutes,15 minutes,30 minutes,1 hour"
   }
  ]
 },
 "panels": [
  {
   "title": "STATION: L1 BUFFER A | Health Score",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  predicted_value  AS health_score\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l1_buffer_a'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    },
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  AVG(predicted_value) OVER (\n    ORDER BY actual_timestamp\n    RANGE BETWEEN INTERVAL '${sma_window}' PRECEDING AND CURRENT ROW\n  ) AS health_trend_sma\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l1_buffer_a'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    }
   ]
  },
  {
   "title": "STATION: L1 BUFFER B | Health Score",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  predicted_value  AS health_score\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l1_buffer_b'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    },
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  AVG(predicted_value) OVER (\n    ORDER BY actual_timestamp\n    RANGE BETWEEN INTERVAL '${sma_window}' PRECEDING AND CURRENT ROW\n  ) AS health_trend_sma\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l1_buffer_b'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    }
   ]
  },
  {
   "title": "STATION: L1 DISPENSER | Health Score",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  predicted_value  AS health_score\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l1_dispenser'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    },
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  AVG(predicted_value) OVER (\n    ORDER BY actual_timestamp\n    RANGE BETWEEN INTERVAL '${sma_window}' PRECEDING AND CURRENT ROW\n  ) AS health_trend_sma\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l1_dispenser'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    }
   ]
  },
  {
   "title": "STATION: L1 INSPECTION | Health Score",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  predicted_value  AS health_score\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l1_inspection'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    },
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  AVG(predicted_value) OVER (\n    ORDER BY actual_timestamp\n    RANGE BETWEEN INTERVAL '${sma_window}' PRECEDING AND CURRENT ROW\n  ) AS health_trend_sma\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l1_inspection'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    }
   ]
  },
  {
   "title": "STATION: L2 BUFFER A | Health Score",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  predicted_value  AS health_score\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l2_buffer_a'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    },
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  AVG(predicted_value) OVER (\n    ORDER BY actual_timestamp\n    RANGE BETWEEN INTERVAL '${sma_window}' PRECEDING AND CURRENT ROW\n  ) AS health_trend_sma\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l2_buffer_a'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    }
   ]
  },
  {
   "title": "STATION: L2 DISPENSER | Health Score",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  predicted_value  AS health_score\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l2_dispenser'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    },
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  AVG(predicted_value) OVER (\n    ORDER BY actual_timestamp\n    RANGE BETWEEN INTERVAL '${sma_window}' PRECEDING AND CURRENT ROW\n  ) AS health_trend_sma\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l2_dispenser'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    }
   ]
  },
  {
   "title": "STATION: L2 INSPECTION | Health Score",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  predicted_value  AS health_score\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l2_inspection'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    },
    {
     "dataset": "glue-dispenser-db",
     "rawSql": "SELECT\n  actual_timestamp AS time,\n  AVG(predicted_value) OVER (\n    ORDER BY actual_timestamp\n    RANGE BETWEEN INTERVAL '${sma_window}' PRECEDING AND CURRENT ROW\n  ) AS health_trend_sma\nFROM model_predictions\nWHERE metric_name  = 'health_score'\n  AND station_name = 'l2_inspection'\n  AND model_name   = 'isolation_forest'\n  AND $__timeFilter(actual_timestamp)\nORDER BY actual_timestamp"
    }
   ]
  }
 ]
}