"""initial migration

Revision ID: 3952f744f16c
Revises: 
Create Date: 2026-02-20 17:03:42.834582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3952f744f16c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.Text(), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('std_dev', sa.Float(), nullable=True),
    sa.Column('min_limit', sa.Float(), nullable=True),
    sa.Column('max_limit', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_name', 'metric_name', name='uq_baseline_station_metric')
    )
    op.create_index('idx_baseline_station', 'baseline_metrics', ['station_name', 'metric_name'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('station_name', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('service_name', sa.Text(), nullable=True),
    sa.Column('log_message', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_errors_severity', 'error_logs', ['severity', 'timestamp'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('actual_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('predicted_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('station_name', sa.Text(), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_predictions_station_metric', 'model_predictions', ['station_name', 'metric_name', 'predicted_timestamp'], unique=False)
    op.create_table('process_metrics',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('station_name', sa.Text(), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('state_context', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_component', 'process_metrics', ['station_name', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_metrics_component', table_name='process_metrics')
    op.drop_table('process_metrics')
    op.drop_index('idx_model_predictions_station_metric', table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index('idx_errors_severity', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index('idx_baseline_station', table_name='baseline_metrics')
    op.drop_table('baseline_metrics')
    # ### end Alembic commands ###
