machine:
  name: "Glue_Dispenser_Standardized"
  version: "3.0"

topology:
  # ==========================================
  # ENTRY: CED
  # ==========================================
  - id: "ced_station"
    class: "CEDStation"
    is_entry: true
    logic_template: "ced_station"
    next_nodes: ["exit_sink"]

  # ==========================================
  # ENTRY: CED Maintenance
  # ==========================================
  - id: "ced_maintenance"
    class: "CEDMaintenance"
    is_entry: true
    logic_template: "ced_maintenance"
    next_nodes: ["exit_sink"]

  # ==========================================
  # ENTRY: CED Maintenance
  # ==========================================
  - id: "gantry_positioning"
    class: "GantryPositioning"
    is_entry: true
    logic_template: "gantry_positioning"
    next_nodes: ["exit_sink"]

  # ==========================================
  # EXIT SINK
  # ==========================================
  - id: "exit_sink"
    class: "SinkComponent"
    is_exit: true
    logic_template: "exit_sink"
    hardware_link: {}