stateDiagram-v2
    direction LR
    [*] --> IDLE
    IDLE --> HOLDING: PALLET_ARRIVAL
    HOLDING --> PALLET_RELEASING: STOPPER_KEEPING_DOWN
    HOLDING --> STOPPER_LOWERING: STOPPER_DOWN_START
    STOPPER_LOWERING --> PALLET_RELEASING: STOPPER_DOWN_DONE
    PALLET_RELEASING --> IDLE: STOPPER_KEEPING_UP
    PALLET_RELEASING --> STOPPER_RAISING: STOPPER_UP_START
    STOPPER_RAISING --> IDLE: STOPPER_UP_DONE