stateDiagram-v2
    [*] --> IDLE
    
    IDLE --> ENTRY_UNCLAMPING: UNCLAMP_START
    ENTRY_UNCLAMPING --> POST_ENTRY_UNCLAMP: UNCLAMP_DONE
    POST_ENTRY_UNCLAMP --> PALLET_LIFTING_1: PALLET_ZPOS_1_START
    POST_ENTRY_UNCLAMP --> ENTRY_UNCLAMPING: UNCLAMP_START
    PALLET_LIFTING_1 --> ENTRY_CLAMPING: CLAMP_START
    ENTRY_CLAMPING --> PALLET_STOPPER_PREP: CLAMP_DONE
    PALLET_STOPPER_PREP --> PALLET_STOPPER_RELEASING: PALLET_STOPPER_OUT_START
    PALLET_STOPPER_RELEASING --> GANTRY_PREP: PALLET_STOPPER_OUT_DONE
    GANTRY_PREP --> COMBINED_POSITIONING: COMBINED_POSITIONING_START
    COMBINED_POSITIONING --> DISPENSING: COMBINED_POSITIONING_END
    DISPENSING --> PALLET_LOWERING_1: PALLET_ZPOS_1_START
    PALLET_LOWERING_1 --> PALLET_STOPPER_LOCKING: PALLET_STOPPER_IN_START
    PALLET_STOPPER_LOCKING --> PRE_EXIT_UNCLAMPING: PALLET_STOPPER_IN_DONE
    PRE_EXIT_UNCLAMPING --> EXIT_UNCLAMPING: UNCLAMP_START
    EXIT_UNCLAMPING --> POST_EXIT_UNCLAMP: UNCLAMP_DONE
    POST_EXIT_UNCLAMP --> PALLET_LOWERING_0: PALLET_ZPOS_0_START
    POST_EXIT_UNCLAMP --> EXIT_UNCLAMPING: UNCLAMP_START
    PALLET_LOWERING_0 --> STOPPER_LOWERING: STOPPER_DOWN_START
    STOPPER_LOWERING --> PALLET_RELEASING: STOPPER_DOWN_DONE
    PALLET_RELEASING --> STOPPER_RAISING: STOPPER_UP_START
    STOPPER_RAISING --> IDLE: STOPPER_UP_DONE