stateDiagram-v2
    [*] --> IDLE
    
    IDLE --> GANTRY_PREP: LIFTER_KEEPING_UP
    GANTRY_PREP --> GANTRY_POSITIONING: GANTRY_POSITIONING_START
    GANTRY_POSITIONING --> INSPECTION: GANTRY_POSITIONING_DONE
    INSPECTION --> POST_INSPECTION: INSPECTION_DONE
    POST_INSPECTION --> POST_LIFTER_DOWN: LIFTER_KEEPING_DOWN
    POST_LIFTER_DOWN --> PALLET_RELEASING: STOPPER_KEEPING_UP
    PALLET_RELEASING --> IDLE: STOPPER_KEEPING_DOWN