stateDiagram-v2
    
    [*] --> IDLE
    
    IDLE --> PRE_SCANNING: PALLET_ARRIVAL
    PRE_SCANNING --> SCANNING: AT_BARCODE
    SCANNING --> POST_SCANNING: SCAN_SUCCESS
    SCANNING --> SCANNING: SCAN_ATTEMPT_FAIL
    SCANNING --> POST_SCANNING: SCAN_FAILURE
    POST_SCANNING --> CARRIER_MOTION: CARRIER_STARTED
    CARRIER_MOTION --> STOPPER_LOWERING: STOPPER_DOWN_START
    STOPPER_LOWERING --> PALLET_RELEASING: STOPPER_DOWN_DONE
    PALLET_RELEASING --> STOPPER_RAISING: STOPPER_UP_START
    STOPPER_RAISING --> IDLE: STOPPER_UP_DONE

    